# Generated by Django 6.0.6 on 2026-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_is_suspended_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="cover_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(default="ศรีสะเกษ", max_length=100),
        ),
    ]
