# Generated by Django 6.0.6 on 2026-09-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_cover_image_profile_cover_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_login_browser",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="เบราว์เซอร์ล่าสุด"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_login_device",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="อุปกรณ์ล่าสุด"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_login_ip",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="IP ล่าสุด"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_login_location",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="สถานที่ล่าสุด"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_login_os",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="ระบบปฏิบัติการล่าสุด"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="signup_browser",
            field=models.CharField(
                blank=True,
                default="Google Chrome",
                max_length=80,
                null=True,
                verbose_name="เบราว์เซอร์ตอนสมัคร",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="signup_device",
            field=models.CharField(
                blank=True,
                default="คอมพิวเตอร์ (Desktop)",
                max_length=80,
                null=True,
                verbose_name="อุปกรณ์ตอนสมัคร",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="signup_ip",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="IP ตอนสมัคร"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="signup_location",
            field=models.CharField(
                blank=True,
                default="ศรีสะเกษ, ประเทศไทย",
                max_length=150,
                null=True,
                verbose_name="สถานที่ตอนสมัคร",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="signup_method",
            field=models.CharField(
                blank=True,
                default="เว็บฟอร์ม",
                max_length=50,
                null=True,
                verbose_name="ช่องทางการสมัคร",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="signup_os",
            field=models.CharField(
                blank=True,
                default="Windows 10/11",
                max_length=80,
                null=True,
                verbose_name="ระบบปฏิบัติการตอนสมัคร",
            ),
        ),
    ]
