# Generated by Django 6.0.6 on 2026-09-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_profile_last_login_browser_profile_last_login_device_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cover_position",
            field=models.IntegerField(
                default=50, verbose_name="ตำแหน่งภาพพื้นหลังแนวตั้ง (%)"
            ),
        ),
    ]
