# Generated by Django 6.0.6 on 2026-09-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_cover_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bonus_xp",
            field=models.IntegerField(default=0, verbose_name="โบนัสแต้ม XP พิเศษ"),
        ),
        migrations.AddField(
            model_name="profile",
            name="custom_level",
            field=models.IntegerField(
                default=0, verbose_name="ระดับเลเวลกำหนดเอง (0=คำนวณตามจริง, 1-5)"
            ),
        ),
    ]
