# Generated by Django 6.0.6 on 2026-09-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="ที่นี่มีอะไร?", max_length=100)),
                (
                    "site_description",
                    models.CharField(
                        blank=True,
                        default="ค้นพบสถานที่น่าสนใจผ่านเรื่องราวและรูปภาพ",
                        max_length=255,
                    ),
                ),
                (
                    "default_province",
                    models.CharField(default="ศรีสะเกษ", max_length=100),
                ),
                ("default_lat", models.FloatField(default=15.112)),
                ("default_lng", models.FloatField(default=104.318)),
                ("allow_user_registration", models.BooleanField(default=True)),
                ("require_post_moderation", models.BooleanField(default=False)),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, default="support@whatshere.com", max_length=254
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("report", "รายงานปัญหา"),
                    ("user", "ผู้ใช้งาน"),
                    ("post", "โพสต์"),
                    ("location", "สถานที่"),
                    ("system", "ระบบ"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
